### ISSUE TITLE
Editor Build Failed

### ISSUE THREAD

**Issue by Workshopshed** [autostep/AutoStep#73]
Pulled all latest files. Built the AutoStep without issue.
Trying to build AutoStep.Editor errors with the following

Store\CodeWindow\ChangeFileEffect.cs(35,35): error CS1061: 'IProjectCompiler' does not contain a definition for 'Compile' and no accessible extension method 'Compile' accepting a first argument of type 'IProjectCompiler' could be found (are you missing a using directive or an assembly reference?) [C:\Users\owner\Desktop\Andy\AutoStep\AutoStep.Editor\src\Client\AutoStep.Editor.Client.csproj]   
Store\CodeWindow\CodeChangeEffect.cs(33,35): error CS1061: 'IProjectCompiler' does not contain a definition for 'Compile' and no accessible extension method 'Compile' accepting a first argument of type 'IProjectCompiler' could be found (are you missing a using directive or an assembly reference?) [C:\Users\owner\Desktop\Andy\AutoStep\AutoStep.Editor\src\Client\AutoStep.Editor.Client.csproj]   

Build FAILED.

**Comment by alistairjevans** [comment]
Yeah, not entirely surprised. The AutoStep.Editor repo should be considered frozen really. In the early days of the project I was considering making my own editor for the testing process, but settled eventually on the [VS Code extension](https://github.com/autostep/AutoStep.VsCode) instead as a way to get to an initial version quickly.

If we ever want to come back to building a custom editor,  or we want a web-based demo window for AutoStep, we can bring that repo up to compatibility with latest AutoStep.

**Comment by alistairjevans** [comment]
I've added a note to the repo's readme to that effect.
